apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/drupal-data"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
    spec:
      initContainers:
      - name: init-sites-volume
        image: drupal:8.6
        command: [ "/bin/bash", "-c" ]
        args : [ 'cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R' ]
        volumeMounts:
        - name: drupalstorage
          mountPath: /data
      containers:
      - name: drupal
        image: drupal:8.6
        imagePullPolicy: Always
        volumeMounts:
        - name: drupalstorage
          subPath: modules
          mountPath: /var/www/html/modules
        - name: drupalstorage
          subPath: profiles
          mountPath: /var/www/html/profiles
        - name: drupalstorage
          subPath: sites
          mountPath: /var/www/html/sites
        - name: drupalstorage
          subPath: themes
          mountPath: /var/www/html/themes
      volumes:
      - name: drupalstorage
        persistentVolumeClaim:
          claimName: drupal-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30095
    port: 30095
  selector:
    app: drupal    